local_backend: true # Comment out when not in use

backend:
  name: git-gateway
  branch: main # original: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'routes'
    label: 'Routes'
    label_singular: 'Route'
    folder: 'content/routes'
    create: true
    delete: true
    description: 'Database of all the routes available on the website.'
    slug: "{{slug}}-{{length}}km"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'route-template'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false}
      - { label: 'Hero Image', name: 'heroImage', widget: 'image', required: false, allow_multiple: false}
      - label: 'Overview'
        name: 'overview'
        widget: 'object'
        summary: '{{fields.startPoint}}: {{length}}km'
        hint: 'This is information for the overview of the route page and SEO.'
        fields:
          - { label: 'Length (km)', name: 'length', widget: 'number', value_type: 'float', step: 0.01 }
          - { label: 'Elevation (m)', name: 'elevation', widget: 'number', value_type: 'float', step: 1, default: 0, required: false }
          - { label: 'Time Allowed (Hrs)', name: 'timeAllowed', hint: 'Given hours:minutes format.', widget: 'string', pattern: ['^([\d]{1,2})([:][0-5][0-9]){1}$', Must be H:mm or HH:mm format.], required: false, default: "" }
          - { label: 'OS Map', name: 'osMapLink', widget: 'string', required: false }
          - { label: 'Start Point', name: 'startPoint', widget: 'relation', collection: 'locations', value_field: 'title', search_fields: ['title']}
          - { label: 'End Point', name: 'endPoint', widget: 'relation', collection: 'locations', value_field: 'title', search_fields: ['title'], hint: 'Not required. Use only for point to point walks.', required: false, default: ""}
          - { label: 'Brief description', name: 'excerpt', widget: 'string', pattern: ['^(.){10,160}$', "Must have between 10 and 160 characters"], required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        required: false
        fields:
          - { label: "Image", name: "image", widget: "image", allow_multiple: false }
          - { label: "Caption", name: "caption", widget: "string", required: false}

  - name: 'locations'
    label: 'Locations'
    label_singular: 'Location'
    folder: 'content/locations'
    create: true
    delete: true
    description: 'Database of all route start points. Should be the point of public transport.'
    slug: "{{slug}}"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'location-template'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image', allow_multiple: false }
      - label: "Location"
        name: "location"
        widget: "object"
        required: true
        collapsed: true
        summary: "{{fields.latitude}} : {{fields.longitude}}"
        fields: 
          - {label: "Latitude", name: "latitude", widget: "number", value_type: 'float', step: 0.000001, min: -90, max: 90}
          - {label: "Longitude", name: "longitude", widget: "number", value_type: 'float', step: 0.000001, min: -180, max: 180}
      - { label: 'Travel time', name: 'travelTime', hint: 'Given in minutes, or hours:minutes format.', widget: 'string', pattern: ['^([\d]{1,2})([:][0-5][0-9])?$', Must be minutes up to 99 or HH:mm format.] }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', pattern: ['^(.){10,160}$', "Must have between 10 and 160 characters"]}
      - { label: 'Reachable by', name: 'type', widget: 'select', options: ["Train", "Metrolink", "Bus", "Car"], multiple: true, min: 1}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'upcoming'
    label: 'Planned Routes'
    label_singular: 'Upcoming Route'
    folder: 'content/upcomingRoutes'
    create: true
    delete: true
    description: 'Upcoming route with date'
    slug: "{{slug}}"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'upcoming-template'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Route', name: 'route', widget: 'relation', collection: 'routes', value_field: 'title', search_fields: ['title']}
      - { label: 'Meet time', name: 'meetTime', hint: 'Must be HH:mm format in 24hr time', widget: 'string', pattern: ['^([\d]{1,2})([:][0-5][0-9]){1}$', Must be HH:mm format in 24hr time.] }
      - { label: 'Meet location', name: 'meetLocation', widget: 'string' }
      - { label: 'Meet date', name: 'meetDate', widget: 'datetime', time_format: 'DD.MM.YYYY', default: ''}

    # - name: 'upcomingNoDate'
    # label: 'Unplanned Routes'
    # label_singular: 'Unplanned Route'
    # folder: 'content/upcomingRoutes'
    # create: true
    # delete: true
    # description: 'Upcoming route with no date'
    # slug: "{{slug}}"
    # media_folder: ''
    # public_folder: ''
    # path: '{{slug}}/index'
    # filter: {field: "meetDate", value: ""}
    # fields:
    #   - { label: 'Title', name: 'title', widget: 'string' }
    #   - { label: 'Route', name: 'route', widget: 'relation', collection: 'routes', value_field: 'title', search_fields: ['title']}
    #   - { label: 'Meet time', name: 'meetTime', widget: 'datetime', time_format: 'HH:mm' }
    #   - { label: 'Meet location', name: 'meetLocation', widget: 'string' }
    #   - { label: 'Meet date', name: 'meetDate', widget: 'datetime', time_format: 'DD.MM.YYYY', default: ''}
  
  - name: 'articles'
    label: 'Articles'
    label_singular: 'Article'
    folder: 'content/articles'
    create: true
    delete: true
    description: 'Database of all articles in the website.'
    slug: "{{slug}}"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'article-template'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image', allow_multiple: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'highlightedArticles'
    label: 'Highlighted Articles'
    label_singular: 'Highlighted Article'
    folder: 'content/highlightedArticle'
    create: true
    delete: true
    description: 'List of the highlighted articles to display on first page.'
    slug: "{{slug}}"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Article', name: 'article', widget: 'relation', collection: 'articles', value_field: 'title', search_fields: ['title']}